apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-annonsemottak
  namespace: teampam
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 9016
  liveness:
    path: /isAlive
    initialDelay: 20
  readiness:
    path: /isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 2
  cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 2000m
      memory: 1500Mi
    requests:
      cpu: 500m
      memory: 500Mi
  prometheus:
    enabled: true
    path: /actuator/prometheus
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
  filesFrom:
    - secret: pam-annonsemottak-env-secret
      mountPath: /var/run/secrets/nais.io/vault
  gcp:
    sqlInstances:
      - name: pam-annonsemottak
        type: POSTGRES_11
        tier: db-custom-1-3840
        diskType: SSD
        highAvailability: true
        diskSize: 30
        diskAutoresize: true
        autoBackupTime: "03:30"
        maintenanceWindow:
          day: 7
          hour: 23
        databases:
          - name: pamannonsemottak
            envVarPrefix: DB
        cascadingDelete: false
  accessPolicy:
    outbound:
      external:
        - host: cache.api.finn.no
          ports:
            - port: 443
              name: https
              protocol: HTTPS
        - host: api.dexi.io
          ports:
            - port: 443
              name: https
              protocol: HTTPS
        - host: services.api.no
          ports:
            - port: 443
              name: https
              protocol: HTTPS
        - host: stilling.adresseavisen.no
          ports:
            - port: 443
              name: https
              protocol: HTTPS
    inbound:
      rules:
        - application: pam-ad
        - application: pam-stillingsregistrering-api
  env:
    - name: SCHEDULER_ENABLED
      value: "{{ scheduler_enabled }}"
