apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: pam-annonsemottak
  namespace: default
  labels:
    team: teampam
spec:
  image: {{ image }}
  port: 9016
  liveness:
    path: /isAlive
    initialDelay: 20
  readiness:
    path: /isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 2
  cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 2000m
      memory: 1500Mi
    requests:
      cpu: 500m
      memory: 500Mi
  vault:
    enabled: true
  webproxy: true
  prometheus:
    enabled: true
    path: /actuator/prometheus
  ingresses:
  {{#each ingress as |url|}}
     - {{url}}
  {{/each}}
