apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: pam-annonsemottak
  namespace: teampam
  labels:
    team: teampam
spec:
  port: 9016
  liveness:
    path: /isAlive
    initialDelay: 20
  readiness:
    path: /isReady
    initialDelay: 20
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      memory: 4096Mi
    requests:
      cpu: 113m
      memory: 2048Mi
  prometheus:
    enabled: true
    path: /actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  gcp:
    sqlInstances:
      - name: pam-annonsemottak
        type: POSTGRES_18
        tier: db-custom-1-3840
        diskType: SSD
        highAvailability: true
        diskSize: 30
        diskAutoresize: true
        maintenance:
          day: 7
          hour: 23
        databases:
          - name: pamannonsemottak
            envVarPrefix: DB
        cascadingDelete: false
  accessPolicy:
    outbound:
      external:
        - host: cache.api.finn.no
          ports:
            - port: 443
        - host: services.api.no
          ports:
            - port: 443
    inbound:
      rules:
        - application: pam-ad
        - application: pam-stillingsregistrering-api
  envFrom:
    - secret: pam-annonsemottak-secret
  env:
    - name: SCHEDULER_ENABLED
      value: "true"
    - name: ANNONSEMOTTAK_TOPIC
      value: teampam.annonsemottak-v1
    - name: OUTBOX_KAFKA_ENABLED
      value: "true"
    - name: OUTBOX_SCHEDULER_ENABLED
      value: "true"
