package no.nav.pam.annonsemottak.receivers.solr.fetch;

public class StillingSolrBeanFieldNames {
    public static final String ADRESSELINJE1 = "ADRESSELINJE1";
    public static final String ADRESSEPOSTNR = "ADRESSEPOSTNR";
    public static final String ADRESSEPOSTSTED = "ADRESSEPOSTSTED";
    public static final String ANSETTELSESFORHOLD = "ANSETTELSESFORHOLD";
    public static final String ANTALLSTILLINGER = "ANTALLSTILLINGER";
    public static final String ARBEIDSGIVERNAVN = "ARBEIDSGIVERNAVN";
    public static final String ARBEIDSORDNING = "ARBEIDSORDNING";
    public static final String BEDRIFTSPRESENTASJON = "BEDRIFTSPRESENTASJON";
    public static final String FYLKE = "FYLKE";
    public static final String GEOGRAFISKOMRADE = "GEOGRAFISKOMRADE";
    public static final String HELTIDDELTID = "HELTIDDELTID";
    public static final String ID = "ID";
    public static final String KILDETEKST = "KILDETEKST";
    public static final String MEDIUMTEKST = "MEDIUMTEKST";
    public static final String KOMMUNE = "KOMMUNE";
    public static final String KOMMUNIKASJON_EPOST = "KOMMUNIKASJON_EPOST";
    public static final String KOMMUNIKASJON_TELEFON = "KOMMUNIKASJON_TELEFON";
    public static final String KOMMUNIKASJON_URL = "KOMMUNIKASJON_URL";
    public static final String KOMPETANSE = "KOMPETANSE";
    public static final String KONTAKTPERSON = "KONTAKTPERSON";
    public static final String LAND = "LAND";
    public static final String LONNSINFO = "LONNSINFO";
    public static final String PRAKSIS = "PRAKSIS";
    public static final String PUBLISERES_FRA = "PUBLISERES_FRA";
    public static final String REG_DATO = "REG_DATO";
    public static final String SERTIFIKAT = "SERTIFIKAT";
    public static final String SISTEPUBLISERINGSDATO = "SISTEPUBLISERINGSDATO";
    public static final String SOKNADSFRIST = "SOKNADSFRIST";
    public static final String SOKNADSENDES = "SOKNADSENDES";
    public static final String SOKNADMERKES = "SOKNADMERKES";
    public static final String STILLINGSBESKRIVELSE = "STILLINGSBESKRIVELSE";
    public static final String STILLINGSPROSENT = "STILLINGSPROSENT";
    public static final String STILLINGSTATUSKODE = "STILLINGSTATUSKODE";
    public static final String STILLINGSTYPE_5 = "STILLINGSTYPE_5";
    public static final String TITTEL = "TITTEL";
    public static final String UTDANNING = "UTDANNING";

    public static final String TILDATO = "TILDATO";
    public static final String FRADATO = "FRADATO";
    public static final String AKTIVERINGSDATO = "AKTIVERINGSDATO";
    // tre treff: public static final String ANSFORHMERKNAD = "ANSFORHMERKNAD";
    public static final String ARBEIDSSTEDMERKNAD = "ARBEIDSSTEDMERKNAD";
    // sju treff: public static final String STORRELSEMAALEENHET = "STORRELSEMAALEENHET";
    public static final String KOMMUNETEKST = "KOMMUNETEKST";
    public static final String KOMMUNIKASJON_FAKS = "KOMMUNIKASJON_FAKS";
    public static final String ADRESSELINJE2 = "ADRESSELINJE2";
    // ni treff: public static final String ADRESSELINJE3 = "ADRESSELINJE3";
    public static final String STILLINGSNUMMER = "STILLINGSNUMMER";
}
