-- TODO: Remove after transition from PAM-STILLING is complete

CREATE TABLE FEEDTASK(
  ID NUMERIC(19,0) NOT NULL,
  FEED_NAME varchar(255) NOT NULL,
  LAST_RUN_DATE TIMESTAMP,
  UNIQUE(FEED_NAME),
  CONSTRAINT PK_FEEDTASK PRIMARY KEY (ID)
);

CREATE SEQUENCE FEEDTASK_SEQ START WITH 1;