server:
  port: 9016
application:
  version: @project.version@
spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
management:
  endpoint:
    prometheus:
      access: read-only
    metrics:
      access: read-only
    mappings:
      access: read-only
  endpoints:
    web:
      exposure:
        include: ["prometheus", "metrics", "mappings"]
scheduler:
  enabled: ${SCHEDULER_ENABLED:false}
kafka:
  brokers: ${KAFKA_BROKERS:http://localhost:1337}
  credstorepass: ${KAFKA_CREDSTORE_PASSWORD:}
  truststorepath: ${KAFKA_TRUSTSTORE_PATH:}
  keystorepath: ${KAFKA_KEYSTORE_PATH:}
appname: ${NAIS_APP_NAME:}
outbox:
  kafka:
    enabled: ${OUTBOX_KAFKA_ENABLED:false}
    topic: ${ANNONSEMOTTAK_TOPIC:teampam.annonsemottak-1}
  scheduler:
    enabled: ${OUTBOX_SCHEDULER_ENABLED:false}
