package no.nav.pam.annonsemottak.receivers.amedia.filter;
enum FilterAarsak {
    WEBCRUITER,
    REFERERT_LENKE_MANGLER,
    ENDRER_TEKST_FOR_SOKEKNAPP,
    FOR_LITE_STILLINGSBESKRIVELSE,
    EKSKLUDERT_KILDE,
    ARBEIDSGIVER_FILTRES_BORT,
    FELTLENGDE_OVERSKREDET,
    UKJENT
}
