name: build-deploy-feature
on:
  push:
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENCE"
      - "CODEOWNERS"
    branches:
      - feature/*
jobs:
  build-and-deploy-feature:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '14.x'
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: build and test
        run:  mvn clean install
      - name: build and push docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          APPLICATION=$(echo $GITHUB_REPOSITORY | cut -d "/" -f 2)
          SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-8)
          VERSION_TAG=${GITHUB_REF##*/}-$SHORT_SHA
          IMAGE=ghcr.io/$GITHUB_REPOSITORY:$VERSION_TAG
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build . --pull -t $IMAGE
          echo "$GITHUB_TOKEN" | docker login --username "$GITHUB_REPOSITORY" --password-stdin ghcr.io
          docker push $IMAGE
      - name: deploy to dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: naiserator.yml
          VARS: naiserator-dev.json
